platform :ios, '6.0'
pod 'BlocksKit'
pod 'AFNetworking'
pod 'SVProgressHUD'
pod 'TestFlightSDK'
#pod 'MagicalRecord'
#pod 'Reachability'
#pod 'SDWebImage'
#pod 'SSKeychain'
#pod 'NSData+Base64'
#pod 'MKStoreKit'